name: PlanC6
version: '1.0'
main: de.theredno.planc.Main
api-version: '1.21'
authors: [ TheRedNo, Illy-Dev ]
website: theredno.de
commands:
  give_all_items:
    permission: planc.give
  setlevel:
    permission: planc.level
  gem_menu:
  addgem:
    permission: planc.add
  getgem:
    permission: planc.get
  createcrate:
    permission: planc.crate